#!/usr/bin/env bash
set -euo pipefail

# 将 Unla 的数据库配置映射到 llm-config-gateway 所需的环境变量，
# 生成 lite-backend/llm-config-gateway/.env.local 供本地启动使用。

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="${SCRIPT_DIR%/scripts}"
UNLA_DIR="${ROOT_DIR}/Unla"
LLM_DIR="${ROOT_DIR}/llm-config-gateway"

UNLA_ENV="${UNLA_DIR}/.env"
OUT_ENV="${LLM_DIR}/.env.local"

if [[ ! -f "$UNLA_ENV" ]]; then
  echo "[ERROR] 未找到 Unla 环境文件: $UNLA_ENV" >&2
  exit 1
fi

mkdir -p "$LLM_DIR"

# 直接加载 Unla 的 .env（本地脚本环境）
# 注意：该操作会把 .env 中的变量导入当前 shell，会影响后续 echo 环境。
set -a
source "$UNLA_ENV"
set +a

# 兜底默认值（如果 .env 未定义或为空）
: "${GATEWAY_DB_HOST:=localhost}"
: "${GATEWAY_DB_PORT:=5434}"
: "${GATEWAY_DB_USER:=postgres}"
: "${GATEWAY_DB_PASSWORD:=}"
: "${GATEWAY_DB_NAME:=unla}"
: "${GATEWAY_DB_SSL_MODE:=disable}"
: "${UNLA_DB_TABLE_PREFIX:=unla_}"

cat >"$OUT_ENV" <<EOF
# Auto-generated by scripts/configure_llm_gateway_from_unla_env.sh
# llm-config-gateway will read these via os.Getenv

LLM_DB_HOST=${GATEWAY_DB_HOST}
LLM_DB_PORT=${GATEWAY_DB_PORT}
LLM_DB_USER=${GATEWAY_DB_USER}
LLM_DB_PASSWORD=${GATEWAY_DB_PASSWORD}
LLM_DB_NAME=${GATEWAY_DB_NAME}
LLM_DB_SSLMODE=${GATEWAY_DB_SSL_MODE}

# Unla table prefix (used by sync-from-unla)
UNLA_DB_TABLE_PREFIX=${UNLA_DB_TABLE_PREFIX}

# Optional runtime tuning
LLM_GATEWAY_PORT=9050
LLM_UPSTREAM_TIMEOUT_MS=60000
LLM_UPSTREAM_RETRY=2
EOF

echo "[OK] 已生成 llm-config-gateway 本地环境文件: $OUT_ENV"
echo "[HINT] 启动示例: (cd \"$LLM_DIR\" && set -a && source ./.env.local && set +a && go run .)"
