module.exports = {
  apps: [
    {
      name: 'llm-gateway',
      script: './bin/llm-config-gateway',
      cwd: '/Users/wxn/Desktop/NextAgentLite/services',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        PORT: '9050',
      },
      error_file: './logs/llm-gateway-error.log',
      out_file: './logs/llm-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'unla-apiserver',
      script: './bin/unla-apiserver',
      args: '-c ./configs/unla-configs/apiserver.yaml',
      cwd: '/Users/wxn/Desktop/NextAgentLite/services',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        PORT: '5234',
      },
      error_file: './logs/unla-apiserver-error.log',
      out_file: './logs/unla-apiserver-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'unla-mcp-gateway',
      script: './bin/unla-mcp-gateway',
      args: '-c ./configs/unla-configs/mcp-gateway.yaml',
      cwd: '/Users/wxn/Desktop/NextAgentLite/services',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        PORT: '5235',
      },
      error_file: './logs/unla-mcp-gateway-error.log',
      out_file: './logs/unla-mcp-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'unla-web',
      script: 'serve',
      args: '-s ./web/dist -l 5173',
      cwd: '/Users/wxn/Desktop/NextAgentLite/services',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        PORT: '5173',
      },
      error_file: './logs/unla-web-error.log',
      out_file: './logs/unla-web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'deepscrape',
      script: './node/deepscrape/dist/index.js',
      cwd: '/Users/wxn/Desktop/NextAgentLite/services',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
      },
      error_file: './logs/deepscrape-error.log',
      out_file: './logs/deepscrape-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'datagraph',
      script: './datagraph/start.sh',
      cwd: '/Users/wxn/Desktop/NextAgentLite/services',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        PORT: '9622',
        HOST: '0.0.0.0',
      },
      error_file: './logs/datagraph-error.log',
      out_file: './logs/datagraph-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
